In [1]:
import numpy as np

In [2]:
{'a':[1,2,3]}

{'a': [1, 2, 3]}

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [10]:
nombres = ['Carolina','Jairo','Jefferson']
nombres[0]

'Carolina'

In [11]:
nombres = ['Carolina','Jairo','Jefferson']
nombres[1]

'Jairo'

In [12]:
nombres = ['Carolina','Jairo','Jefferson']
nombres[2]

'Jefferson'

In [13]:
nombres_np = np.array(nombres)
nombres_np

array(['Carolina', 'Jairo', 'Jefferson'], dtype='<U9')

In [14]:
nombres_np[1]

'Jairo'

In [17]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
lista1 = [1,2,3]
lista2 = [4,5,6]

In [23]:
lista1

[1, 2, 3]

In [24]:
lista2

[4, 5, 6]

In [28]:
[lista1, lista2]

[[1, 2, 3], [4, 5, 6]]

In [27]:
np.array([lista1, lista2])

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
type([lista1, lista2])

list

In [30]:
type(np.array)


builtin_function_or_method

In [33]:
np.array([lista1, lista2,[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr1 = [1,2,3]
arr2 = [4,5,6]

In [50]:
arr1 + arr2

[1, 2, 3, 4, 5, 6]