In [4]:
import numpy as np

In [7]:
array = np.loadtxt('prueba.csv', delimiter= ',')
array

array([[  11., 1000.,   19.,    8.,  101.,    5.,    6.,    5., 1000.],
       [   9.,   17., 1000.,   13.,  101.,   20.,   15.,  101.,   19.],
       [  14.,    4.,   17.,   13.,    4.,   20.,   19.,    4.,   17.],
       [   8.,    8.,   16.,    9.,  101.,   20.,   12., 1000.,   19.],
       [  13.,   11.,   20., 1000.,   14.,    9.,   12.,   16., 1000.],
       [1000.,    5.,   20.,    5.,   14.,    8.,   11.,   15., 1000.],
       [  19.,   14.,   17.,   12.,  101.,  101.,   19.,   18.,  101.],
       [  13.,  101.,   14.,   13.,    7.,   14.,    4., 1000.,   14.],
       [ 101.,    6.,   17., 1000., 1000.,    3.,   16.,   16.,    8.],
       [  15.,   11.,   16.,   16.,   14.,   17.,   17.,   12.,    3.],
       [  12.,   15.,   16.,    3.,    9.,   12.,   15.,    3.,   20.],
       [  17.,   18.,    4.,    6.,    3.,   14.,   18.,   16.,   17.],
       [1000.,    3.,   11., 1000.,    5.,   20.,   16.,    4.,    8.],
       [  16.,    7.,   13.,   20.,  101., 1000.,    8.,   17., 

In [8]:
array = array*2
array

array([[  22., 2000.,   38.,   16.,  202.,   10.,   12.,   10., 2000.],
       [  18.,   34., 2000.,   26.,  202.,   40.,   30.,  202.,   38.],
       [  28.,    8.,   34.,   26.,    8.,   40.,   38.,    8.,   34.],
       [  16.,   16.,   32.,   18.,  202.,   40.,   24., 2000.,   38.],
       [  26.,   22.,   40., 2000.,   28.,   18.,   24.,   32., 2000.],
       [2000.,   10.,   40.,   10.,   28.,   16.,   22.,   30., 2000.],
       [  38.,   28.,   34.,   24.,  202.,  202.,   38.,   36.,  202.],
       [  26.,  202.,   28.,   26.,   14.,   28.,    8., 2000.,   28.],
       [ 202.,   12.,   34., 2000., 2000.,    6.,   32.,   32.,   16.],
       [  30.,   22.,   32.,   32.,   28.,   34.,   34.,   24.,    6.],
       [  24.,   30.,   32.,    6.,   18.,   24.,   30.,    6.,   40.],
       [  34.,   36.,    8.,   12.,    6.,   28.,   36.,   32.,   34.],
       [2000.,    6.,   22., 2000.,   10.,   40.,   32.,    8.,   16.],
       [  32.,   14.,   26.,   40.,  202., 2000.,   16.,   34., 

In [9]:
np.savetxt('prueba3.csv', array, delimiter=',')

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame(array)
df

0       1       2       3       4       5     6       7       8
0     22.0  2000.0    38.0    16.0   202.0    10.0  12.0    10.0  2000.0
1     18.0    34.0  2000.0    26.0   202.0    40.0  30.0   202.0    38.0
2     28.0     8.0    34.0    26.0     8.0    40.0  38.0     8.0    34.0
3     16.0    16.0    32.0    18.0   202.0    40.0  24.0  2000.0    38.0
4     26.0    22.0    40.0  2000.0    28.0    18.0  24.0    32.0  2000.0
5   2000.0    10.0    40.0    10.0    28.0    16.0  22.0    30.0  2000.0
6     38.0    28.0    34.0    24.0   202.0   202.0  38.0    36.0   202.0
7     26.0   202.0    28.0    26.0    14.0    28.0   8.0  2000.0    28.0
8    202.0    12.0    34.0  2000.0  2000.0     6.0  32.0    32.0    16.0
9     30.0    22.0    32.0    32.0    28.0    34.0  34.0    24.0     6.0
10    24.0    30.0    32.0     6.0    18.0    24.0  30.0     6.0    40.0
11    34.0    36.0     8.0    12.0     6.0    28.0  36.0    32.0    34.0
12  2000.0     6.0    22.0  2000.0    10.0    40.0  32.0     8.0    16.0
13    32.0    14.0    26.0    40.0   202.0  2000.0  16.0    34.0  2000.0
14    12.0    36.0    16.0    30.0    28.0     8.0  14.0    22.0  2000.0
15  2000.0    12.0    14.0    40.0    18.0    18.0   8.0    28.0    26.0
16    36.0    14.0    14.0    36.0    32.0  2000.0   8.0    32.0   202.0
17    36.0   202.0    26.0  2000.0  2000.0    22.0  36.0  2000.0    18.0

In [16]:
import openpyxl
df.to_excel('prueba.xlsx')

In [17]:
prueba2 = np.loadtxt('https://raw.githubusercontent.com/laboratoriolide/new-dimensions/main/Python/prueba2.csv',delimiter=',',dtype='str')
prueba2

array([['\ufeffNombre', 'Edad', 'Peso_kg', 'Altura_m'],
       ['Ana', '33', '60', '1.6'],
       ['Manuel', '38', '80', '1.82'],
       ['Daniela', '29', '70', '1.54'],
       ['Jose', '25', '100', '1.7'],
       ['Sara', '40', '95', '1.75']], dtype='<U8')

In [24]:
prueba2= np.loadtxt('https://raw.githubusercontent.com/laboratoriolide/new-dimensions/main/Python/prueba2.csv',delimiter=',',skiprows= 1, dtype='str')
prueba2

array([['Ana', '33', '60', '1.6'],
       ['Manuel', '38', '80', '1.82'],
       ['Daniela', '29', '70', '1.54'],
       ['Jose', '25', '100', '1.7'],
       ['Sara', '40', '95', '1.75']], dtype='<U7')

In [19]:
columnas = prueba2[0,:]
columnas

array(['\ufeffNombre', 'Edad', 'Peso_kg', 'Altura_m'], dtype='<U8')

In [46]:
print(columnas)

['Ana' '33' '60' '1.6']


In [21]:
prueba2[1:,0]

array(['Ana', 'Manuel', 'Daniela', 'Jose', 'Sara'], dtype='<U8')

In [25]:
prueba2[0:,1]

array(['Edad', '33', '38', '29', '25', '40'], dtype='<U8')

In [26]:
prueba2[0:,2]

array(['Peso_kg', '60', '80', '70', '100', '95'], dtype='<U8')

In [29]:
datos = np.loadtxt('https://raw.githubusercontent.com/laboratoriolide/new-dimensions/main/Python/prueba2.csv',delimiter=',',skiprows= 1,usecols= [1,2,3])
datos

array([[ 33.  ,  60.  ,   1.6 ],
       [ 38.  ,  80.  ,   1.82],
       [ 29.  ,  70.  ,   1.54],
       [ 25.  , 100.  ,   1.7 ],
       [ 40.  ,  95.  ,   1.75]])

In [30]:
np.mean(datos[:,0])

33.0

In [34]:
for col in np.arange(0,datos.shape[1]):  
 print(np.mean(datos[:,col]))


33.0
81.0
1.682


In [42]:
for row in np.arange(0,datos.shape[0]):  
  print(np.mean(datos[row,:]))

31.53333333333333
39.94
33.513333333333335
42.233333333333334
45.583333333333336


In [37]:
datos.shape

(5, 3)

In [38]:
datos.shape[0]

5

In [39]:
datos.shape[1]

3

In [43]:
#bucles en columnas
np.mean(datos,axis=0)

array([33.   , 81.   ,  1.682])

In [44]:
#bucles en filas
np.mean(datos,axis=1)

array([31.53333333, 39.94      , 33.51333333, 42.23333333, 45.58333333])