In [2]:
import numpy as np
from glob import glob

In [3]:
glob("*.csv")

['prueba.csv']

In [4]:
lista_archivos = glob('*.csv')
lista_archivos 

['prueba.csv']

In [5]:
mascara = np.loadtxt('https://raw.githubusercontent.com/laboratoriolide/new-dimensions/bc9b4e8b5544ea5070486443e5474384c166c7dd/Python/mascara.csv',delimiter= ',')
mascara

array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
mascara.dtype

dtype('float64')

In [7]:
prueba = np.loadtxt (fname= 'https://raw.githubusercontent.com/laboratoriolide/new-dimensions/main/Python/prueba.csv',delimiter=',')

In [8]:
print(prueba)

[[11.  0. 19.  8. 10.  5.  6.  5.  1.]
 [ 9. 17.  1. 13. 10. 20. 15. 10. 19.]
 [14.  4. 17. 13.  4. 20. 19.  4. 17.]
 [ 8.  8. 16.  9. 10. 20. 12.  1. 19.]
 [13. 11. 20.  1. 14.  9. 12. 16.  1.]
 [ 2.  5. 20.  5. 14.  8. 11. 15.  1.]
 [19. 14. 17. 12. 10. 10. 19. 18. 10.]
 [13. 10. 14. 13.  7. 14.  4.  2. 14.]
 [10.  6. 17.  1.  0.  3. 16. 16.  8.]
 [15. 11. 16. 16. 14. 17. 17. 12.  3.]
 [12. 15. 16.  3.  9. 12. 15.  3. 20.]
 [17. 18.  4.  6.  3. 14. 18. 16. 17.]
 [ 2.  3. 11.  0.  5. 20. 16.  4.  8.]
 [16.  7. 13. 20. 10.  1.  8. 17.  1.]
 [ 6. 18.  8. 15. 14.  4.  7. 11.  2.]
 [ 0.  6.  7. 20.  9.  9.  4. 14. 13.]
 [18.  7.  7. 18. 16.  0.  4. 16. 10.]
 [18. 10. 13.  2.  1. 11. 18.  1.  9.]]


In [9]:
#prueba[mascara] 
mascara=mascara.astype("bool")

In [10]:
prueba[mascara == 1]

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [11]:
mascara == 1

array([[False, False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False,  True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False, False,  True],
       [False,  True, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, 

In [12]:
prueba+mascara

array([[11.,  0., 19.,  8., 11.,  5.,  6.,  5.,  1.],
       [ 9., 17.,  1., 13., 11., 20., 15., 11., 19.],
       [14.,  4., 17., 13.,  4., 20., 19.,  4., 17.],
       [ 8.,  8., 16.,  9., 11., 20., 12.,  1., 19.],
       [13., 11., 20.,  1., 14.,  9., 12., 16.,  1.],
       [ 2.,  5., 20.,  5., 14.,  8., 11., 15.,  1.],
       [19., 14., 17., 12., 11., 11., 19., 18., 11.],
       [13., 11., 14., 13.,  7., 14.,  4.,  2., 14.],
       [11.,  6., 17.,  1.,  0.,  3., 16., 16.,  8.],
       [15., 11., 16., 16., 14., 17., 17., 12.,  3.],
       [12., 15., 16.,  3.,  9., 12., 15.,  3., 20.],
       [17., 18.,  4.,  6.,  3., 14., 18., 16., 17.],
       [ 2.,  3., 11.,  0.,  5., 20., 16.,  4.,  8.],
       [16.,  7., 13., 20., 11.,  1.,  8., 17.,  1.],
       [ 6., 18.,  8., 15., 14.,  4.,  7., 11.,  2.],
       [ 0.,  6.,  7., 20.,  9.,  9.,  4., 14., 13.],
       [18.,  7.,  7., 18., 16.,  0.,  4., 16., 11.],
       [18., 11., 13.,  2.,  1., 11., 18.,  1.,  9.]])

In [13]:
prueba[mascara] = prueba[mascara]*10
prueba

array([[ 11.,   0.,  19.,   8., 100.,   5.,   6.,   5.,   1.],
       [  9.,  17.,   1.,  13., 100.,  20.,  15., 100.,  19.],
       [ 14.,   4.,  17.,  13.,   4.,  20.,  19.,   4.,  17.],
       [  8.,   8.,  16.,   9., 100.,  20.,  12.,   1.,  19.],
       [ 13.,  11.,  20.,   1.,  14.,   9.,  12.,  16.,   1.],
       [  2.,   5.,  20.,   5.,  14.,   8.,  11.,  15.,   1.],
       [ 19.,  14.,  17.,  12., 100., 100.,  19.,  18., 100.],
       [ 13., 100.,  14.,  13.,   7.,  14.,   4.,   2.,  14.],
       [100.,   6.,  17.,   1.,   0.,   3.,  16.,  16.,   8.],
       [ 15.,  11.,  16.,  16.,  14.,  17.,  17.,  12.,   3.],
       [ 12.,  15.,  16.,   3.,   9.,  12.,  15.,   3.,  20.],
       [ 17.,  18.,   4.,   6.,   3.,  14.,  18.,  16.,  17.],
       [  2.,   3.,  11.,   0.,   5.,  20.,  16.,   4.,   8.],
       [ 16.,   7.,  13.,  20., 100.,   1.,   8.,  17.,   1.],
       [  6.,  18.,   8.,  15.,  14.,   4.,   7.,  11.,   2.],
       [  0.,   6.,   7.,  20.,   9.,   9.,   4.,  14.,

In [14]:
mascara2 = prueba < 3
prueba[mascara2] = 0

In [15]:
mascara2 = prueba < 3
prueba[mascara2] = 1000

In [16]:
prueba

array([[  11., 1000.,   19.,    8.,  100.,    5.,    6.,    5., 1000.],
       [   9.,   17., 1000.,   13.,  100.,   20.,   15.,  100.,   19.],
       [  14.,    4.,   17.,   13.,    4.,   20.,   19.,    4.,   17.],
       [   8.,    8.,   16.,    9.,  100.,   20.,   12., 1000.,   19.],
       [  13.,   11.,   20., 1000.,   14.,    9.,   12.,   16., 1000.],
       [1000.,    5.,   20.,    5.,   14.,    8.,   11.,   15., 1000.],
       [  19.,   14.,   17.,   12.,  100.,  100.,   19.,   18.,  100.],
       [  13.,  100.,   14.,   13.,    7.,   14.,    4., 1000.,   14.],
       [ 100.,    6.,   17., 1000., 1000.,    3.,   16.,   16.,    8.],
       [  15.,   11.,   16.,   16.,   14.,   17.,   17.,   12.,    3.],
       [  12.,   15.,   16.,    3.,    9.,   12.,   15.,    3.,   20.],
       [  17.,   18.,    4.,    6.,    3.,   14.,   18.,   16.,   17.],
       [1000.,    3.,   11., 1000.,    5.,   20.,   16.,    4.,    8.],
       [  16.,    7.,   13.,   20.,  100., 1000.,    8.,   17., 

In [17]:
np.mean(prueba[mascara])

100.0

In [18]:
prueba.shape

(18, 9)

In [19]:
resultado = prueba+mascara

In [20]:
np.savetxt("prueba.csv", resultado,delimiter=',')

In [21]:
revision = np.loadtxt("prueba.csv", delimiter=',')
revision

array([[  11., 1000.,   19.,    8.,  101.,    5.,    6.,    5., 1000.],
       [   9.,   17., 1000.,   13.,  101.,   20.,   15.,  101.,   19.],
       [  14.,    4.,   17.,   13.,    4.,   20.,   19.,    4.,   17.],
       [   8.,    8.,   16.,    9.,  101.,   20.,   12., 1000.,   19.],
       [  13.,   11.,   20., 1000.,   14.,    9.,   12.,   16., 1000.],
       [1000.,    5.,   20.,    5.,   14.,    8.,   11.,   15., 1000.],
       [  19.,   14.,   17.,   12.,  101.,  101.,   19.,   18.,  101.],
       [  13.,  101.,   14.,   13.,    7.,   14.,    4., 1000.,   14.],
       [ 101.,    6.,   17., 1000., 1000.,    3.,   16.,   16.,    8.],
       [  15.,   11.,   16.,   16.,   14.,   17.,   17.,   12.,    3.],
       [  12.,   15.,   16.,    3.,    9.,   12.,   15.,    3.,   20.],
       [  17.,   18.,    4.,    6.,    3.,   14.,   18.,   16.,   17.],
       [1000.,    3.,   11., 1000.,    5.,   20.,   16.,    4.,    8.],
       [  16.,    7.,   13.,   20.,  101., 1000.,    8.,   17., 