In [15]:
import numpy as np

In [16]:
import pandas as pd

In [17]:
array = np.array([1,2,3,4,5,6])
array

array([1, 2, 3, 4, 5, 6])

In [18]:
array[(array > 3)]

array([4, 5, 6])

In [19]:
array[(array > 3) & (array < 6)]

array([4, 5])

In [20]:
datos = np.loadtxt (fname= 'https://raw.githubusercontent.com/laboratoriolide/new-dimensions/main/Python/prueba.csv',delimiter=',')

In [21]:
print(datos)

[[11.  0. 19.  8. 10.  5.  6.  5.  1.]
 [ 9. 17.  1. 13. 10. 20. 15. 10. 19.]
 [14.  4. 17. 13.  4. 20. 19.  4. 17.]
 [ 8.  8. 16.  9. 10. 20. 12.  1. 19.]
 [13. 11. 20.  1. 14.  9. 12. 16.  1.]
 [ 2.  5. 20.  5. 14.  8. 11. 15.  1.]
 [19. 14. 17. 12. 10. 10. 19. 18. 10.]
 [13. 10. 14. 13.  7. 14.  4.  2. 14.]
 [10.  6. 17.  1.  0.  3. 16. 16.  8.]
 [15. 11. 16. 16. 14. 17. 17. 12.  3.]
 [12. 15. 16.  3.  9. 12. 15.  3. 20.]
 [17. 18.  4.  6.  3. 14. 18. 16. 17.]
 [ 2.  3. 11.  0.  5. 20. 16.  4.  8.]
 [16.  7. 13. 20. 10.  1.  8. 17.  1.]
 [ 6. 18.  8. 15. 14.  4.  7. 11.  2.]
 [ 0.  6.  7. 20.  9.  9.  4. 14. 13.]
 [18.  7.  7. 18. 16.  0.  4. 16. 10.]
 [18. 10. 13.  2.  1. 11. 18.  1.  9.]]


In [22]:
type(datos)

numpy.ndarray

In [23]:
datos.ndim

2

In [24]:
datos.dtype

dtype('float64')

In [25]:
datos[0,0]

11.0

In [26]:
f'El valor de mi matriz es: {datos [0,0]}'

'El valor de mi matriz es: 11.0'

In [27]:
datos[3:5,3:6]

array([[ 9., 10., 20.],
       [ 1., 14.,  9.]])

In [28]:
#for i in range(3,5):
#print(i)
range(3,5)

range(3, 5)

In [30]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [32]:
np.mean(datos)

10.592592592592593

In [33]:
np.sum(datos)

1716.0

In [34]:
np.sum(datos[:,0])

203.0

In [35]:
datos[:,0]

array([11.,  9., 14.,  8., 13.,  2., 19., 13., 10., 15., 12., 17.,  2.,
       16.,  6.,  0., 18., 18.])

In [36]:
np.amax(datos)

20.0

In [37]:
np.amin(datos)

0.0

In [38]:
np.std(datos)

5.993366245898543

In [39]:
print('El maximo de mis datos es:', np.amax (datos))

El maximo de mis datos es: 20.0


In [40]:
print('El minimo de mi ultimo final es:', np.amin(datos[-1]))

El minimo de mi ultimo final es: 1.0


In [41]:
datos[(datos < 15) & (datos > 10)]

array([11., 13., 14., 13., 12., 13., 11., 14., 12., 14., 11., 14., 12.,
       13., 14., 13., 14., 14., 11., 14., 12., 12., 12., 14., 11., 13.,
       14., 11., 14., 13., 13., 11.])

In [42]:
datos_10_15 = datos[(datos < 15) & (datos > 10)]
datos_10_15

array([11., 13., 14., 13., 12., 13., 11., 14., 12., 14., 11., 14., 12.,
       13., 14., 13., 14., 14., 11., 14., 12., 12., 12., 14., 11., 13.,
       14., 11., 14., 13., 13., 11.])

In [43]:
np.mean(datos_10_15)

12.71875